<?php
$cata = $block->getChildHtml('home-floor3-cata');
?>
<?php if ($cata): ?>
    <div class="floor" id="home-floor3">
        <div class="floor__header">
            <?php echo $block->getChildHtml('home-floor3-cata');?>
        </div>
        <div class="floor__body">
            <div class="wrapper">
                <div class="wrapper-left">
                    <div class="w50 h100">
                        <div class="floor__body__slick slick "
                             data-slick='{"slidesToShow": 1, "slidesToScroll": 1,"dots":true,"arrows":false,"autoplay":true}'>
                            <?php echo $this->getChildHtml('home-floor3-left') ?>
                        </div>
                    </div>
                </div>
                <div class="wrapper-middle">
                    <?php echo $this->getChildHtml('home-floor3-middle') ?>
                </div>
                <div class="wrapper-right">
                    <?php echo $this->getChildHtml('home-floor3-right') ?>
                </div>
            </div>
            <div class="floor-brand">
                <p class="title"><?php echo __('Hot Brand'); ?></p>
                <div class="slick slick--brand"
                     data-slick='{"slidesToShow": 4, "slidesToScroll": 1,"dots":false,"vertical":true}'>
                    <?php echo $this->getChildHtml('recommend-attribute-list-third'); ?>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>