<?php
$cata = $block->getChildHtml('home-floor2-cata');
?>
<?php if ($cata): ?>
    <div class="floor" id="home-floor2">
        <div class="floor__header">
            <?php echo $block->getChildHtml('home-floor2-cata');?>
        </div>
        <div class="floor__body">
            <div class="wrapper">
                <div class="wrapper-left">
                    <?php echo $this->getChildHtml('home-floor2-left') ?>
                </div>
                <div class="wrapper-middle">
                    <?php echo $this->getChildHtml('home-floor2-middle') ?>
                </div>
                <div class="wrapper-right">
                    <?php echo $this->getChildHtml('home-floor2-right') ?>
                </div>
            </div>
            <div class="floor-brand">
                <p class="title"><?php echo __('Hot Brand'); ?></p>
                <div class="slick slick--brand"
                     data-slick='{"slidesToShow": 4, "slidesToScroll": 1,"dots":false,"vertical":true,"autoplay":true}'>
                    <?php echo $this->getChildHtml('recommend-attribute-list-sec'); ?>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>