<a class="banner" href="<?php echo $this->getHref();?>"  alt="<?php echo $this->__('advertisement')?>" title="<?php echo $this->__('advertisement')?>">
    <img class="lazy" src="<?php echo $this->getSkinUrl('images/placeholder.gif');?>" data-original="<?php echo $this->getSrc();?>" title="<?php echo $this->__('advertisement')?>" alt="<?php echo $this->__('advertisement')?>">
    <noscript>
        <img src="<?php echo $this->getSrc();?>" title="<?php echo $this->__('advertisement')?>" alt="<?php echo $this->__('advertisement')?>">
    </noscript>
</a>