<a class="banner" href="<?php echo $this->getHref();?>"  alt="<?php echo __('advertisement')?>" title="<?php echo __('advertisement')?>">
    <img class="lazy" src="<?php echo $block->getViewFileUrl('images/placeholder.gif');?>" data-original="<?php echo $this->getSrc();?>" title="<?php echo $this->__('advertisement')?>" alt="<?php echo __('advertisement')?>">
    <noscript>
        <img src="<?php echo $this->getSrc();?>" title="<?php echo __('advertisement')?>" alt="<?php echo __('advertisement')?>">
    </noscript>
</a>