<?php
/**
 * Created by PhpStorm.
 * User: HaoMingyang
 * Date: 2017/4/18
 * Time: 10:10
 */
namespace Sanv\Banner\Block;

class Banner extends \Magento\Framework\View\Element\Template
{
    public function getDbData()
    {
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $array_data = $objectManager->get('\Sanv\Banner\Model\ResourceModel\Post\Collection')->getData();
        return $array_data;
    }

    public function getImageUrl(){
        //get meidia url
        $meidaUrl = $this->getUrl('pub/media');
        //set images base url
        $baseImageUrl = $meidaUrl.'sanv/banner/post/image';

        return $baseImageUrl;
    }
    
    public function getBaseUrl()
    {
        return parent::getBaseUrl(); // TODO: Change the autogenerated stub
    }
}
